# Generated by Django 4.2.1 on 2023-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0002_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
    ]
