# Generated by Django 4.2.1 on 2023-05-21 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0003_remove_employee_base_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='deductions',
            new_name='insurance',
        ),
        migrations.AddField(
            model_name='salary',
            name='otherDeductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
