# Generated by Django 4.2.1 on 2023-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0004_rename_deductions_salary_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='otherDeductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
